import type { Metadata } from 'next'
import Head from 'next/head';
import { poppins } from '@/app/ui/fonts'
import './globals.css';
import Navbar from './ui/Navbar';

export const metadata: Metadata = {
  title: 'Tang',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
